2024-04-14 18:25:08,993 INFO    StreamThr :57803 [internal.py:wandb_internal():86] W&B internal server running at pid: 57803, started at: 2024-04-14 18:25:08.992288
2024-04-14 18:25:08,994 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status
2024-04-14 18:25:09,002 INFO    WriterThread:57803 [datastore.py:open_for_write():87] open: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/run-g7xvzdgi.wandb
2024-04-14 18:25:09,002 DEBUG   SenderThread:57803 [sender.py:send():379] send: header
2024-04-14 18:25:09,028 DEBUG   SenderThread:57803 [sender.py:send():379] send: run
2024-04-14 18:25:09,680 INFO    SenderThread:57803 [dir_watcher.py:__init__():211] watching files in: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files
2024-04-14 18:25:09,680 INFO    SenderThread:57803 [sender.py:_start_run_threads():1124] run started: g7xvzdgi with start time 1713090308.993456
2024-04-14 18:25:09,700 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: check_version
2024-04-14 18:25:09,700 DEBUG   SenderThread:57803 [sender.py:send_request():406] send_request: check_version
2024-04-14 18:25:10,499 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: run_start
2024-04-14 18:25:10,510 DEBUG   HandlerThread:57803 [system_info.py:__init__():26] System info init
2024-04-14 18:25:10,511 DEBUG   HandlerThread:57803 [system_info.py:__init__():41] System info init done
2024-04-14 18:25:10,511 INFO    HandlerThread:57803 [system_monitor.py:start():194] Starting system monitor
2024-04-14 18:25:10,512 INFO    SystemMonitor:57803 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-04-14 18:25:10,512 INFO    HandlerThread:57803 [system_monitor.py:probe():214] Collecting system info
2024-04-14 18:25:10,513 INFO    SystemMonitor:57803 [interfaces.py:start():190] Started cpu monitoring
2024-04-14 18:25:10,513 DEBUG   HandlerThread:57803 [system_info.py:probe():150] Probing system
2024-04-14 18:25:10,513 INFO    SystemMonitor:57803 [interfaces.py:start():190] Started disk monitoring
2024-04-14 18:25:10,516 INFO    SystemMonitor:57803 [interfaces.py:start():190] Started gpuapple monitoring
2024-04-14 18:25:10,516 INFO    SystemMonitor:57803 [interfaces.py:start():190] Started memory monitoring
2024-04-14 18:25:10,528 INFO    SystemMonitor:57803 [interfaces.py:start():190] Started network monitoring
2024-04-14 18:25:10,533 DEBUG   HandlerThread:57803 [system_info.py:_probe_git():135] Probing git
2024-04-14 18:25:10,586 DEBUG   HandlerThread:57803 [system_info.py:_probe_git():143] Probing git done
2024-04-14 18:25:10,586 DEBUG   HandlerThread:57803 [system_info.py:probe():198] Probing system done
2024-04-14 18:25:10,586 DEBUG   HandlerThread:57803 [system_monitor.py:probe():223] {'os': 'macOS-14.2.1-arm64-arm-64bit', 'python': '3.10.13', 'heartbeatAt': '2024-04-14T10:25:10.513621', 'startedAt': '2024-04-14T10:25:08.976198', 'docker': None, 'cuda': None, 'args': ('--model_name_or_path', '/Users/a58/Downloads/pretrain_model/Qwen/Qwen1.5-0.5B-Chat', '--do_train', 'True', '--per_device_train_batch_size', '2', '--gradient_accumulation_steps', '1', '--learning_rate', '5e-5', '--weight_decay', '0', '--max_grad_norm', '1.0', '--num_train_epochs', '2.0', '--block_size', '32', '--train_file', '/Users/a58/Downloads/my_test/data/data_sft/renting_data_train_7000_improved_prompting3.json', '--output_dir', '/Users/a58/Downloads/MoE_Train/outputs', '--overwrite_output_dir', '--logging_dir', '/Users/a58/Downloads/MoE_Train/outputs', '--save_strategy', 'epoch', '--save_total_limit', '1', '--logging_strategy', 'steps', '--logging_steps', '10', '--report_to', 'wandb', '--trust_remote_code', 'True', '--template', 'qwen', '--q_lora', 'False', '--use_lora', 'True', '--lora_r', '8', '--lora_alpha', '32', '--lora_dropout', '0.05', '--lora_target_modules', 'q_proj', 'v_proj', 'k_proj', 'o_proj', 'gate_proj', 'down_proj', 'up_proj'), 'state': 'running', 'program': '/Users/a58/Downloads/MoE_Train/finetune/run.py', 'codePathLocal': 'run.py', 'codePath': 'finetune/run.py', 'git': {'remote': 'https://github.com/Darrenzeng/MoE_Train.git', 'commit': '5769742f6f9e686c6324ed68457139359bbaa7b0'}, 'email': 'zengyufei@58.com', 'root': '/Users/a58/Downloads/MoE_Train', 'host': '58deMacBook-Pro-2.local', 'username': 'a58', 'executable': '/Users/a58/anaconda3/envs/llama_factory/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 13.36923599243164}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2024-04-14 18:25:10,586 INFO    HandlerThread:57803 [system_monitor.py:probe():224] Finished collecting system info
2024-04-14 18:25:10,586 INFO    HandlerThread:57803 [system_monitor.py:probe():227] Publishing system info
2024-04-14 18:25:10,586 DEBUG   HandlerThread:57803 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-04-14 18:25:10,688 INFO    Thread-12 :57803 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files/conda-environment.yaml
2024-04-14 18:25:15,656 DEBUG   HandlerThread:57803 [system_info.py:_save_conda():222] Saving conda packages done
2024-04-14 18:25:15,657 INFO    HandlerThread:57803 [system_monitor.py:probe():229] Finished publishing system info
2024-04-14 18:25:15,665 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:25:15,665 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: keepalive
2024-04-14 18:25:15,665 DEBUG   SenderThread:57803 [sender.py:send():379] send: files
2024-04-14 18:25:15,665 INFO    SenderThread:57803 [sender.py:_save_file():1390] saving file wandb-metadata.json with policy now
2024-04-14 18:25:15,709 INFO    Thread-12 :57803 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files/conda-environment.yaml
2024-04-14 18:25:15,709 INFO    Thread-12 :57803 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files/wandb-metadata.json
2024-04-14 18:25:15,979 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: python_packages
2024-04-14 18:25:15,981 DEBUG   SenderThread:57803 [sender.py:send_request():406] send_request: python_packages
2024-04-14 18:25:15,982 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: stop_status
2024-04-14 18:25:15,983 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-14 18:25:15,985 DEBUG   SenderThread:57803 [sender.py:send_request():406] send_request: stop_status
2024-04-14 18:25:16,380 DEBUG   SenderThread:57803 [sender.py:send():379] send: telemetry
2024-04-14 18:25:16,380 DEBUG   SenderThread:57803 [sender.py:send():379] send: config
2024-04-14 18:25:16,381 DEBUG   SenderThread:57803 [sender.py:send():379] send: metric
2024-04-14 18:25:16,381 DEBUG   SenderThread:57803 [sender.py:send():379] send: telemetry
2024-04-14 18:25:16,382 DEBUG   SenderThread:57803 [sender.py:send():379] send: metric
2024-04-14 18:25:16,382 WARNING SenderThread:57803 [sender.py:send_metric():1341] Seen metric with glob (shouldn't happen)
2024-04-14 18:25:16,382 DEBUG   SenderThread:57803 [sender.py:send():379] send: telemetry
2024-04-14 18:25:16,712 INFO    Thread-12 :57803 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files/requirements.txt
2024-04-14 18:25:16,712 INFO    Thread-12 :57803 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files/output.log
2024-04-14 18:25:16,790 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/g7xvzdgi/wandb-metadata.json?Expires=1713176716&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rK2WvBHMK1rLwrNbD7Zs4bLkLiQog04EvWtdme1kY%2BZthuF3Os1clkKbdWPsicawDUd%2FR%2Bxgm8og%2FiyqKEENe7HaTphXhljEjrIowd15qvlsMXap0Fe5nSlhElmozStTG5hF2eYOljGRu8lfXlrQSG7uPApiN303U7a6ZIKUPontO0ax%2F%2F6GiatLDj5SroGj7aJhLcFWMQe9i7zSUOfczxsjaG9GQybyzeAD4ZXh28%2F%2Bcd1xFXApWzu12etck5cA6l%2FTbnWXia4MfMV3MVrVmJUK5nbAtpxpjlsQX0rwVHomk6MyyIW5vOoN0BxeJrOXw%2Bji6XHW9dCg4IkdbZjYfw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-14 18:25:16,790 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2449'}
2024-04-14 18:25:16,790 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-14 18:25:17,923 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/g7xvzdgi/wandb-metadata.json?Expires=1713176716&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rK2WvBHMK1rLwrNbD7Zs4bLkLiQog04EvWtdme1kY%2BZthuF3Os1clkKbdWPsicawDUd%2FR%2Bxgm8og%2FiyqKEENe7HaTphXhljEjrIowd15qvlsMXap0Fe5nSlhElmozStTG5hF2eYOljGRu8lfXlrQSG7uPApiN303U7a6ZIKUPontO0ax%2F%2F6GiatLDj5SroGj7aJhLcFWMQe9i7zSUOfczxsjaG9GQybyzeAD4ZXh28%2F%2Bcd1xFXApWzu12etck5cA6l%2FTbnWXia4MfMV3MVrVmJUK5nbAtpxpjlsQX0rwVHomk6MyyIW5vOoN0BxeJrOXw%2Bji6XHW9dCg4IkdbZjYfw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-14 18:25:17,923 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2449'}
2024-04-14 18:25:17,923 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-14 18:25:18,721 INFO    Thread-12 :57803 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files/output.log
2024-04-14 18:25:20,322 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/g7xvzdgi/wandb-metadata.json?Expires=1713176716&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rK2WvBHMK1rLwrNbD7Zs4bLkLiQog04EvWtdme1kY%2BZthuF3Os1clkKbdWPsicawDUd%2FR%2Bxgm8og%2FiyqKEENe7HaTphXhljEjrIowd15qvlsMXap0Fe5nSlhElmozStTG5hF2eYOljGRu8lfXlrQSG7uPApiN303U7a6ZIKUPontO0ax%2F%2F6GiatLDj5SroGj7aJhLcFWMQe9i7zSUOfczxsjaG9GQybyzeAD4ZXh28%2F%2Bcd1xFXApWzu12etck5cA6l%2FTbnWXia4MfMV3MVrVmJUK5nbAtpxpjlsQX0rwVHomk6MyyIW5vOoN0BxeJrOXw%2Bji6XHW9dCg4IkdbZjYfw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-14 18:25:20,322 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2449'}
2024-04-14 18:25:20,322 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-14 18:25:20,322 INFO    wandb-upload_0:57803 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2760, in upload_file
    response = self._upload_file_session.put(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2791, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2760, in upload_file
    response = self._upload_file_session.put(
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/a58/anaconda3/envs/llama_factory/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-04-14 18:25:20,392 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:25:24,651 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/g7xvzdgi/wandb-metadata.json?Expires=1713176716&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rK2WvBHMK1rLwrNbD7Zs4bLkLiQog04EvWtdme1kY%2BZthuF3Os1clkKbdWPsicawDUd%2FR%2Bxgm8og%2FiyqKEENe7HaTphXhljEjrIowd15qvlsMXap0Fe5nSlhElmozStTG5hF2eYOljGRu8lfXlrQSG7uPApiN303U7a6ZIKUPontO0ax%2F%2F6GiatLDj5SroGj7aJhLcFWMQe9i7zSUOfczxsjaG9GQybyzeAD4ZXh28%2F%2Bcd1xFXApWzu12etck5cA6l%2FTbnWXia4MfMV3MVrVmJUK5nbAtpxpjlsQX0rwVHomk6MyyIW5vOoN0BxeJrOXw%2Bji6XHW9dCg4IkdbZjYfw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-14 18:25:24,651 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2449'}
2024-04-14 18:25:24,651 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-14 18:25:25,409 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:25:30,446 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:25:30,983 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: stop_status
2024-04-14 18:25:30,983 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-14 18:25:30,984 DEBUG   SenderThread:57803 [sender.py:send_request():406] send_request: stop_status
2024-04-14 18:25:33,158 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/g7xvzdgi/wandb-metadata.json?Expires=1713176716&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rK2WvBHMK1rLwrNbD7Zs4bLkLiQog04EvWtdme1kY%2BZthuF3Os1clkKbdWPsicawDUd%2FR%2Bxgm8og%2FiyqKEENe7HaTphXhljEjrIowd15qvlsMXap0Fe5nSlhElmozStTG5hF2eYOljGRu8lfXlrQSG7uPApiN303U7a6ZIKUPontO0ax%2F%2F6GiatLDj5SroGj7aJhLcFWMQe9i7zSUOfczxsjaG9GQybyzeAD4ZXh28%2F%2Bcd1xFXApWzu12etck5cA6l%2FTbnWXia4MfMV3MVrVmJUK5nbAtpxpjlsQX0rwVHomk6MyyIW5vOoN0BxeJrOXw%2Bji6XHW9dCg4IkdbZjYfw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-14 18:25:33,158 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2449'}
2024-04-14 18:25:33,158 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-14 18:25:36,306 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:25:41,332 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:25:41,835 INFO    Thread-12 :57803 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files/config.yaml
2024-04-14 18:25:46,199 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: internal_messages
2024-04-14 18:25:47,605 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: stop_status
2024-04-14 18:25:49,069 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:25:49,117 DEBUG   SenderThread:57803 [sender.py:send_request():406] send_request: stop_status
2024-04-14 18:25:52,387 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: keepalive
2024-04-14 18:25:54,028 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:25:54,432 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/g7xvzdgi/wandb-metadata.json?Expires=1713176716&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rK2WvBHMK1rLwrNbD7Zs4bLkLiQog04EvWtdme1kY%2BZthuF3Os1clkKbdWPsicawDUd%2FR%2Bxgm8og%2FiyqKEENe7HaTphXhljEjrIowd15qvlsMXap0Fe5nSlhElmozStTG5hF2eYOljGRu8lfXlrQSG7uPApiN303U7a6ZIKUPontO0ax%2F%2F6GiatLDj5SroGj7aJhLcFWMQe9i7zSUOfczxsjaG9GQybyzeAD4ZXh28%2F%2Bcd1xFXApWzu12etck5cA6l%2FTbnWXia4MfMV3MVrVmJUK5nbAtpxpjlsQX0rwVHomk6MyyIW5vOoN0BxeJrOXw%2Bji6XHW9dCg4IkdbZjYfw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-14 18:25:54,470 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2449'}
2024-04-14 18:25:54,531 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-14 18:25:59,332 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:26:01,116 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: stop_status
2024-04-14 18:26:01,120 DEBUG   SenderThread:57803 [sender.py:send_request():406] send_request: stop_status
2024-04-14 18:26:04,970 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:26:10,433 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:26:10,551 DEBUG   SystemMonitor:57803 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-04-14 18:26:10,590 DEBUG   SenderThread:57803 [sender.py:send():379] send: telemetry
2024-04-14 18:26:10,591 DEBUG   SenderThread:57803 [sender.py:send():379] send: stats
2024-04-14 18:26:15,665 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:26:16,142 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: stop_status
2024-04-14 18:26:16,149 DEBUG   SenderThread:57803 [sender.py:send_request():406] send_request: stop_status
2024-04-14 18:26:16,547 INFO    Thread-12 :57803 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files/config.yaml
2024-04-14 18:26:32,649 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:26:33,665 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: stop_status
2024-04-14 18:26:33,705 DEBUG   SenderThread:57803 [sender.py:send_request():406] send_request: stop_status
2024-04-14 18:26:34,271 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/darren_qing/Moe_finetuning/g7xvzdgi/wandb-metadata.json?Expires=1713176716&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=rK2WvBHMK1rLwrNbD7Zs4bLkLiQog04EvWtdme1kY%2BZthuF3Os1clkKbdWPsicawDUd%2FR%2Bxgm8og%2FiyqKEENe7HaTphXhljEjrIowd15qvlsMXap0Fe5nSlhElmozStTG5hF2eYOljGRu8lfXlrQSG7uPApiN303U7a6ZIKUPontO0ax%2F%2F6GiatLDj5SroGj7aJhLcFWMQe9i7zSUOfczxsjaG9GQybyzeAD4ZXh28%2F%2Bcd1xFXApWzu12etck5cA6l%2FTbnWXia4MfMV3MVrVmJUK5nbAtpxpjlsQX0rwVHomk6MyyIW5vOoN0BxeJrOXw%2Bji6XHW9dCg4IkdbZjYfw%3D%3D: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-04-14 18:26:34,272 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2449'}
2024-04-14 18:26:34,272 ERROR   wandb-upload_0:57803 [internal_api.py:upload_file():2771] upload_file response body: 
2024-04-14 18:26:36,139 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:26:40,695 DEBUG   SenderThread:57803 [sender.py:send():379] send: stats
2024-04-14 18:26:41,711 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:26:46,127 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: stop_status
2024-04-14 18:26:46,129 DEBUG   SenderThread:57803 [sender.py:send_request():406] send_request: stop_status
2024-04-14 18:26:47,385 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:26:52,404 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:26:55,836 INFO    cpu       :57803 [interfaces.py:monitor():140] Process cpu has exited.
2024-04-14 18:26:55,842 DEBUG   SystemMonitor:57803 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-04-14 18:26:55,842 DEBUG   SystemMonitor:57803 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-04-14 18:26:55,855 DEBUG   SenderThread:57803 [sender.py:send():379] send: stats
2024-04-14 18:26:57,889 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:27:02,909 WARNING StreamThr :57803 [internal.py:is_dead():414] Internal process exiting, parent pid 57636 disappeared
2024-04-14 18:27:02,909 DEBUG   HandlerThread:57803 [handler.py:handle_request():146] handle_request: status_report
2024-04-14 18:27:02,910 ERROR   StreamThr :57803 [internal.py:wandb_internal():152] Internal process shutdown.
2024-04-14 18:27:03,914 INFO    SenderThread:57803 [sender.py:finish():1546] shutting down sender
2024-04-14 18:27:03,914 INFO    HandlerThread:57803 [handler.py:finish():866] shutting down handler
2024-04-14 18:27:03,915 INFO    WriterThread:57803 [datastore.py:close():296] close: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/run-g7xvzdgi.wandb
2024-04-14 18:27:03,915 INFO    HandlerThread:57803 [system_monitor.py:finish():203] Stopping system monitor
2024-04-14 18:27:03,915 INFO    HandlerThread:57803 [interfaces.py:finish():202] Joined cpu monitor
2024-04-14 18:27:03,915 INFO    HandlerThread:57803 [interfaces.py:finish():202] Joined disk monitor
2024-04-14 18:27:03,915 INFO    HandlerThread:57803 [interfaces.py:finish():202] Joined gpuapple monitor
2024-04-14 18:27:03,915 INFO    HandlerThread:57803 [interfaces.py:finish():202] Joined memory monitor
2024-04-14 18:27:03,916 INFO    HandlerThread:57803 [interfaces.py:finish():202] Joined network monitor
2024-04-14 18:27:06,850 INFO    SenderThread:57803 [dir_watcher.py:finish():358] shutting down directory watcher
2024-04-14 18:27:06,918 INFO    SenderThread:57803 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files/output.log
2024-04-14 18:27:06,925 INFO    SenderThread:57803 [dir_watcher.py:finish():388] scan: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files
2024-04-14 18:27:06,926 INFO    SenderThread:57803 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files/requirements.txt requirements.txt
2024-04-14 18:27:06,927 INFO    SenderThread:57803 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files/output.log output.log
2024-04-14 18:27:06,927 INFO    SenderThread:57803 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files/config.yaml config.yaml
2024-04-14 18:27:06,927 INFO    SenderThread:57803 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files/conda-environment.yaml conda-environment.yaml
2024-04-14 18:27:06,930 INFO    SenderThread:57803 [dir_watcher.py:finish():402] scan save: /Users/a58/Downloads/MoE_Train/finetune/wandb/run-20240414_182508-g7xvzdgi/files/wandb-metadata.json wandb-metadata.json
2024-04-14 18:27:06,930 INFO    SenderThread:57803 [file_pusher.py:finish():172] shutting down file pusher
2024-04-14 18:27:06,930 INFO    SenderThread:57803 [file_pusher.py:join():178] waiting for file pusher
2024-04-14 18:27:07,436 INFO    SenderThread:57803 [file_stream.py:finish():614] file stream finish called
2024-04-14 18:27:07,676 INFO    SenderThread:57803 [file_stream.py:finish():618] file stream finish is done
